# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispense_Drug_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_first_name', models.CharField(max_length=70)),
                ('patient_last_name', models.CharField(max_length=70)),
                ('mobile_number', models.CharField(max_length=10)),
                ('last_date_picked', models.DateField()),
                ('next_pick_date', models.DateField()),
                ('weeks_reminder', models.IntegerField(default=0)),
                ('two_day_reminder', models.IntegerField(default=0)),
                ('one_day_later_reminder', models.IntegerField(default=0)),
            ],
        ),
    ]
